name: mealapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.3.1
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  dependencies:
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_core: ^1.16.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  firebase_storage: ^10.2.16
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300   
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

