export '../screens/home/home_screen.dart';
export '../screens/login/login_view.dart';
export '../screens/splash/splash_screen.dart';
export '../screens/patient/patient_dashboard_view.dart';
export '../screens/signup/sign_up_view.dart';
export '../screens/login/login_view.dart';
export '../models/dashboardCategory.dart';
// export '../screens/doctor/doctor_dashboard_view.dart';
export '../screens/doctor/doctor_dashboard_view.dart';
export '../models/doctor.dart';
export '../screens/doctor/doctors_list_screen.dart';
export '../screens/patient_appointment/appointments.dart';
export '../screens/appointment/pickAppointment.dart';
export '../screens/appointment/update_booking_screen.dart';
export '../screens/doctor/doctor_details_screen.dart';
